services:
  web:
    build: 
      context: /apps/web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  api:
    build:
      context: /apps/api
      dockerfile: Dockerfile
  db:
    image: postgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pingbay
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"