version: "3.9"

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/pingbay

  db:
    build:
      context: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pingbay
    volumes:
      - pingbay-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  poller:
    image: curlimages/curl
    container_name: api-poller
    depends_on:
      - api
    command: ["sh", "-c", "while true; do curl http://api:3000/cron/handle-pings; sleep 60; done"]

volumes:
  pingbay-data: